Repository rilling/OSMDashboardConcordia, pull requests merged in 2023-10, with the labels that each got.

#10 Resolved Issue #9 by adding a private constructor to the API Constants Utility class
  build.gradle
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/APIConstants.java
Labels: Technical debt, Group 14

#24 Added a Private constructor to hide the implicit public one
  src/main/java/de/storchp/opentracks/osmplugin/compass/SensorChecker.java
Labels: Group 13

#35 Refactored method onCreate to reduce its Cognitive Complexity.
  build.gradle
  src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java
Labels: Group 13

#37 Add a nested comment explaining why onAccuracyChanged method is empty
  src/main/java/de/storchp/opentracks/osmplugin/compass/AbstractLowPassSensor.java
Labels: Technical debt, Group 13

#41 Update FileUtil.java
  src/main/java/de/storchp/opentracks/osmplugin/utils/FileUtil.java
Labels: Group 15

#43 Code Smell Fix: Fix view paramater issue
  src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java
Labels: group-12

#44 Use isEmpty() to check whether the collection is empty or not.
  src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
Labels: Group 12

#45 Update BaseActivity.java
  src/main/java/de/storchp/opentracks/osmplugin/BaseActivity.java
Labels: Group 12

#55 Modified magnetometerand waypoint
  src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
  src/main/java/de/storchp/opentracks/osmplugin/compass/Magnetometer.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/Waypoint.java
Labels: Group 13

#56 Compass Refactoring
  src/main/java/de/storchp/opentracks/osmplugin/compass/Compass.java
Labels: Technical debt, Group 13

#64 dashboardapi: Use a record instead of passing several parameters
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/Waypoint.java
Labels: Technical debt, Group 14
